 Author : Phuc Bui 
-- Date : 2018-03-29
-- PROC OF TABLE : Thong tin ky thi

-- Them vao bang ky thi
CREATE PROC SP_INSERT_KYTHI
 @NgayBatDauDK varchar(10),
 @TaiKhoan varchar(20),
 @KQ int out
AS
BEGIN
SET @KQ=0
INSERT INTO TTKyThi VALUES('',@NgayBatDauDK,@TaiKhoan)
SET @KQ=1
return @KQ
END
-- Sua thong tin ky thi
GO
CREATE PROC SP_UPDATE_KYTHI
 @KyThi varchar(10),
 @NgayBatDauDK varchar(10),
 @TaiKhoan varchar(20),
 @KQ int out
AS
BEGIN
SET @KQ=0
UPDATE TTKyThi SET  NgayBatDauDK=@NgayBatDauDK,TaiKhoan=@TaiKhoan WHERE KyThi=@KyThi
SET @KQ=1
return @KQ
END
--Xoa ky thi
GO
CREATE PROC SP_DELETE_KYTHI
 @KyThi varchar(10),
 @KQ int out
AS
BEGIN
SET @KQ=0
DELETE FROM TTKyThi WHERE KyThi=@KyThi
SET @KQ=1
return @KQ
END
-- Tao Bang Trung Gian Sinh Cau Hoi
GO
CREATE TABLE RANDOM
(
SoCau int primary key
)
-- Thu Tuc Sinh Ngau Nhien
GO
CREATE PROC SP_RANDOM_MACH
@Upper INT,
@Lower INT
AS
BEGIN
DECLARE @Random INT;
DECLARE @so int,@KT varchar(10)
set @so=1
---- This will create a random number between 1 and 999
DELETE FROM RANDOM
SET @Random = ROUND(((@Upper - @Lower -1) * RAND() + @Lower), 0)
INSERT INTO RANDOM VALUES(@Random)
WHILE (@so<=9)
BEGIN
SET @Random = ROUND(((@Upper - @Lower -1) * RAND() + @Lower), 0)

SET @KT=(SELECT top(1) SoCau FROM RANDOM WHERE SoCau=@Random)
if(@KT  is null)
BEGIN 
INSERT INTO RANDOM VALUES(@Random)
SET @so=@so+1;
END
END
END
-- Sinh De Thi
GO
CREATE PROC SP_RAMDOM_DETHI
 @KYTHI varchar(10),
 @KQ int out
AS
BEGIN
SET @KQ=0
DECLARE @MAKYTHI varchar(10),@MADETHI varchar(10)
SET @MAKYTHI=(SELECT KYTHI FROM TTKyThi WHERE KyThi=@KYTHI)
SET @MADETHI=@MAKYTHI+'001'
INSERT INTO TTDeThi VALUES(@MADETHI,@KYTHI)
SET @MADETHI=@MAKYTHI+'002'
INSERT INTO TTDeThi VALUES(@MADETHI,@KYTHI)
SET @MADETHI=@MAKYTHI+'003'
INSERT INTO TTDeThi VALUES(@MADETHI,@KYTHI)

DECLARE @DAULT int,@CUOILT INT
-- RANDOM 10 Cau LT
SET @CUOILT=0+20*CONVERT(INT,REPLACE(@KYTHI,LEFT(@KYTHI,2),''))
SET @DAULT=@CUOILT-19
EXEC SP_RANDOM_MACH  @DAULT,@CUOILT
DECLARE @MADE varchar(10),@TAM varchar(10),@So int
SET @MADE=@KYTHI+'001'
SET @So=1
WHILE (@So<=10)
BEGIN
SET @TAM=(SELECT TOP(1) SoCau FROM RANDOM)
INSERT INTO TTDeThiCauHoi VALUES(@MADE,@TAM)
DELETE FROM RANDOM WHERE SoCau=@TAM
SET @So=@So+1 
END

SET @CUOILT=0+20*CONVERT(INT,REPLACE(@KYTHI,LEFT(@KYTHI,2),''))
SET @DAULT=@CUOILT-19
EXEC SP_RANDOM_MACH  @DAULT,@CUOILT
SET @MADE=@KYTHI+'002'
SET @So=1
WHILE (@So<=10)
BEGIN
SET @TAM=(SELECT TOP(1) SoCau FROM RANDOM)
INSERT INTO TTDeThiCauHoi VALUES(@MADE,@TAM)
DELETE FROM RANDOM WHERE SoCau=@TAM
SET @So=@So+1 
END

SET @CUOILT=0+20*CONVERT(INT,REPLACE(@KYTHI,LEFT(@KYTHI,2),''))
SET @DAULT=@CUOILT-19
EXEC SP_RANDOM_MACH  @DAULT,@CUOILT
SET @MADE=@KYTHI+'003'
SET @So=1
WHILE (@So<=10)
BEGIN
SET @TAM=(SELECT TOP(1) SoCau FROM RANDOM)
INSERT INTO TTDeThiCauHoi VALUES(@MADE,@TAM)
DELETE FROM RANDOM WHERE SoCau=@TAM
SET @So=@So+1 
END

-- RANDOM 10 Cau Bien Bao
SET @CUOILT=255+20*CONVERT(INT,REPLACE(@KYTHI,LEFT(@KYTHI,2),''))
SET @DAULT=@CUOILT-19
EXEC SP_RANDOM_MACH  @DAULT,@CUOILT
SET @MADE=@KYTHI+'001'
SET @So=1
WHILE (@So<=10)
BEGIN
SET @TAM=(SELECT TOP(1) SoCau FROM RANDOM)
INSERT INTO TTDeThiCauHoi VALUES(@MADE,@TAM)
DELETE FROM RANDOM WHERE SoCau=@TAM
SET @So=@So+1 
END

SET @CUOILT=255+20*CONVERT(INT,REPLACE(@KYTHI,LEFT(@KYTHI,2),''))
SET @DAULT=@CUOILT-19
EXEC SP_RANDOM_MACH  @DAULT,@CUOILT
SET @MADE=@KYTHI+'002'
SET @So=1
WHILE (@So<=10)
BEGIN
SET @TAM=(SELECT TOP(1) SoCau FROM RANDOM)
INSERT INTO TTDeThiCauHoi VALUES(@MADE,@TAM)
DELETE FROM RANDOM WHERE SoCau=@TAM
SET @So=@So+1 
END

SET @CUOILT=255+20*CONVERT(INT,REPLACE(@KYTHI,LEFT(@KYTHI,2),''))
SET @DAULT=@CUOILT-19
EXEC SP_RANDOM_MACH  @DAULT,@CUOILT
SET @MADE=@KYTHI+'003'
SET @So=1
WHILE (@So<=10)
BEGIN
SET @TAM=(SELECT TOP(1) SoCau FROM RANDOM)
INSERT INTO TTDeThiCauHoi VALUES(@MADE,@TAM)
DELETE FROM RANDOM WHERE SoCau=@TAM
SET @So=@So+1 
END

--RanDom 10 Cau Sa Hinh

SET @CUOILT=355+20*CONVERT(INT,REPLACE(@KYTHI,LEFT(@KYTHI,2),''))
SET @DAULT=@CUOILT-19
EXEC SP_RANDOM_MACH  @DAULT,@CUOILT
SET @MADE=@KYTHI+'001'
SET @So=1
WHILE (@So<=10)
BEGIN
SET @TAM=(SELECT TOP(1) SoCau FROM RANDOM)
INSERT INTO TTDeThiCauHoi VALUES(@MADE,@TAM)
DELETE FROM RANDOM WHERE SoCau=@TAM
SET @So=@So+1 
END

SET @CUOILT=355+20*CONVERT(INT,REPLACE(@KYTHI,LEFT(@KYTHI,2),''))
SET @DAULT=@CUOILT-19
EXEC SP_RANDOM_MACH  @DAULT,@CUOILT
SET @MADE=@KYTHI+'002'
SET @So=1
WHILE (@So<=10)
BEGIN
SET @TAM=(SELECT TOP(1) SoCau FROM RANDOM)
INSERT INTO TTDeThiCauHoi VALUES(@MADE,@TAM)
DELETE FROM RANDOM WHERE SoCau=@TAM
SET @So=@So+1 
END
SET @CUOILT=355+20*CONVERT(INT,REPLACE(@KYTHI,LEFT(@KYTHI,2),''))
SET @DAULT=@CUOILT-19
EXEC SP_RANDOM_MACH  @DAULT,@CUOILT
SET @MADE=@KYTHI+'003'
SET @So=1
WHILE (@So<=10)
BEGIN
SET @TAM=(SELECT TOP(1) SoCau FROM RANDOM)
INSERT INTO TTDeThiCauHoi VALUES(@MADE,@TAM)
DELETE FROM RANDOM WHERE SoCau=@TAM
SET @So=@So+1 
END

SET @KQ=1
return @KQ
END

DECLARE @KQ int
EXEC SP_RAMDOM_DETHI 'KT02',@KQ out