//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatHachBangLaiXe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports3
    {
        public string MaHV { get; set; }
        public string TenHV { get; set; }
        public string HoHV { get; set; }
        public string KyThi { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public System.DateTime NgayCapCMND { get; set; }
        public string SoCMND { get; set; }
        public System.DateTime NgaySinh { get; set; }
    }
}
