//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatHachBangLaiXe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public string MaHV { get; set; }
        public string TenHV { get; set; }
        public string HoHV { get; set; }
        public string MaCH { get; set; }
        public string DapAnTS { get; set; }
        public string DapAn { get; set; }
    }
}
