USE SATHACHLAIXE
GO
CREATE TRIGGER TG_KYTHI
ON [TTKyThi]
FOR INSERT
AS
BEGIN
DECLARE @KYTHI VARCHAR(5),@TAM VARCHAR(5);
SET @TAM=(SELECT TOP(1) KyThi FROM TTKyThi ORDER BY KyThi DESC)
SET @TAM=REPLACE(@TAM,LEFT(@TAM,2),'')+1
SET @KYTHI='KT'+
CASE
       WHEN LEN(@TAM)<5
          THEN REPLICATE('0',2-LEN(@TAM))
          ELSE ''
  
END
+ @TAM
UPDATE TTKyThi SET KyThi=@KYTHI WHERE KyThi=''
END
